apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-machinery
  namespace: factory-pipelines
spec:
  params:
  - name: reponame
    type: string
  - name: repourl
    type: string
  - name: revision
    type: string
  - name: gitref
    type: string
  tasks:
  - name: log-start
    params:
    - name: text
      value: 'Push event received to build machinery service $(params.reponame): $(params.repourl)
        - commitid $(params.revision) - ref $(params.gitref)'
    taskRef:
      kind: Task
      name: logger
  - name: git-clone
    params:
    - name: repo
      value: $(params.repourl)
    - name: branch
      value: main
    runAfter:
    - log-start
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: source
      workspace: source
  - name: extract-maven-project-settings
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: extract-maven-project-settings
    params:
    - name: MAVEN_IMAGE
      value: quay.io/tim_speetjens/mvn-quarkus-native-image:0.0.2
    - name: CONTEXT_DIR
      value: machinery-service
    workspaces:
    - name: source
      workspace: source
  - name: git-rev-list-count
    params:
    - name: CONTEXT_DIR
      value: machinery-service
    runAfter:
    - git-clone
    taskRef:
      kind: Task
      name: git-rev-list-count
    workspaces:
    - name: source
      workspace: source
  - name: maven-clean-package
    params:
    - name: GOALS
      value:
      - clean
      - package
      - -Pnative
      - -Dquarkus.native.container-build=false
    - name: MAVEN_IMAGE
      value: quay.io/tim_speetjens/mvn-quarkus-native-image:0.0.2
    - name: CONTEXT_DIR
      value: machinery-service
    runAfter:
    - extract-maven-project-settings
    taskRef:
      kind: Task
      name: maven
    workspaces:
    - name: source
      workspace: source
    - name: maven-settings
      workspace: source
  - name: echo
    params:
    - name: text
      value: "Container image:tag is $(tasks.extract-maven-project-settings.results.projectArtifactId):$(tasks.extract-maven-project-settings.results.projectVersion)-$(tasks.git-rev-list-count.results.git-rev-list-count)"
    runAfter:
    - git-rev-list-count
    - extract-maven-project-settings
    taskRef:
      kind: Task
      name: logger
  workspaces:
  - name: source
  
