---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: pipeline
  triggers: 
  - name: trigger 
    bindings: 
    - kind: TriggerBinding
      ref: event-binding
    template: 
      ref: push
    interceptors: 
    - ref:	
        kind: ClusterInterceptor	
        name: github
      params:	
      - name: secretRef	
        value:	
          secretKey: secretToken	
          secretName: webhook	
      - name: eventTypes	
        value:	
        - push	
