---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
spec:
  serviceAccountName: pipeline
  triggers:
  - name: factory-machinery-service-main-push
    interceptors:
    - name: github filter secret and push event
      ref:
        kind: ClusterInterceptor
        name: github
      params:
      - name: secretRef
        value:
          secretKey: secretToken
          secretName: webhook
      - name: eventTypes
        value:
        - push
    - name: register branch_name
      ref:
        kind: ClusterInterceptor
        name: cel
      params:
      - name: overlays
        value:
        - key: branch_name
          expression: "body.ref.split('/')[2]"
    - name: filter on repository name and branch
      ref:
        kind: ClusterInterceptor
        name: cel
      params:
      - name: filter
        value: >-
          body.repository.full_name == 'qiot-piros/machinery-service' &&
          extensions.branch_name == 'main'
    bindings:
    - kind: TriggerBinding
      ref: event-binding
    template:
      ref: push-machinery
#  - name: smoketest
#    interceptors:
#    - name: github filter secret and push event
#      ref:
#        kind: ClusterInterceptor
#        name: github
#      params:
#      - name: secretRef
#        value:
#          secretKey: secretToken
#          secretName: webhook
#      - name: eventTypes
#        value:
#        - push
#    bindings:
#    - kind: TriggerBinding
#      ref: event-binding
#    template:
#      ref: push-smoketest

