---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: listener
spec:
  serviceAccountName: pipeline
  triggers: 
  - name: trigger 
    bindings: 
    - ref: event-binding
    template: 
      ref: push
    interceptors: 
    - github: 
        secretRef: 
          secretName: webhook
          secretKey: secretToken 
        eventTypes: 
        - push 

