---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: extract-maven-project-settings
  namespace: factory-pipelines
spec:
  params:
  - default: gcr.io/cloud-builders/mvn@sha256:57523fc43394d6d9d2414ee8d1c85ed7a13460cbb268c3cd16d28cfb3859e641
    description: Maven base image
    name: MAVEN_IMAGE
  - default: .
    description: The context directory within the repository for sources on which
      we want to execute maven goals.
    name: CONTEXT_DIR
    type: string
  results:
  - description: project artifactId from pom.xml
    name: projectArtifactId
  - description: project version from pom.xml
    name: projectVersion
  workspaces:
    - name: source
  steps:
  - name: evaluate
    image: $(params.MAVEN_IMAGE)
    script: |
      #!/usr/bin/env bash
      set -e

      cat > $(workspaces.source.path)/mvn-settings.xml <<EOF
      <settings>
        <localRepository>$(workspaces.source.path)/.m2/repository</localRepository>
        <servers>
          <!-- The servers added here are generated from environment variables. Don't change. -->
          <!-- ### SERVER's USER INFO from ENV ### -->
        </servers>
        <mirrors>
          <!-- The mirrors added here are generated from environment variables. Don't change. -->
          <!-- ### mirrors from ENV ### -->
        </mirrors>
        <proxies>
          <!-- The proxies added here are generated from environment variables. Don't change. -->
          <!-- ### HTTP proxy from ENV ### -->
        </proxies>
      </settings>
      EOF


      mvn -s $(workspaces.source.path)/mvn-settings.xml \
        org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
        -Dexpression=project.version -q -DforceStdout > \
        $(results.projectVersion.path)
      mvn -s $(workspaces.source.path)/mvn-settings.xml \
        org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate \
        -Dexpression=project.artifactId -q -DforceStdout > \
        $(results.projectArtifactId.path)
    workingDir: $(workspaces.source.path)/$(params.CONTEXT_DIR)
