---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: logger
  namespace: factory-pipelines
spec:
  params:
  - name: text
    type: string
  steps:
  - image: registry.access.redhat.com/ubi8/ubi-minimal
    name: log
    resources: {}
    script: "DATE=$(date +%d/%m/%Y\\ %T) \necho [$DATE] - $(params.text) \n"
